import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { IRepository } from "../interfaces/search";
import styles from "../styles/Home.module.css";
import { MockSearch } from "../test/mockSearch";

const Home: NextPage = () => {
  const [data, setData] = useState<IRepository[]>();

  useEffect(() => {
    if (!data) {
      new MockSearch().search({}).then((res) => setData(res.items));
    }
  }, [data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Github search</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        {data &&
          data.map((item: IRepository) => {
            return (
              <div>
                <h2>{item.name}</h2>
                <p>{item.description || ""}</p>
                <div>
                  <span>{item.starsCount}</span>
                  <span>{item.licence || ""}</span>
                  <span>{item.updatedAt.toString()}</span>
                </div>
              </div>
            );
          })}
      </main>
    </div>
  );
};

export default Home;
